USE [XolartekDb]
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Active Powercell', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Adhesive Resin', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Bacon', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Batteries', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Blast Powder', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Coal', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Shadowshard Crystal', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Sunbeam Crystal', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Duct Tape', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Flower Petals', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Fibrous Herbs', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Honey', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Rusty Mechanical Parts', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Simple Mechanical Parts', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Sturdy Mechanical Parts', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Sleek Mechanical Parts', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Efficient Mechanical Parts', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Vindertech Mechanical Parts', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Rough Mineral Powder', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Simple Mineral Powder', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Fine-grain Mineral Powder', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Char-Black Mineral Powder', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Oxidized Mineral Powder', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Spectral Mineral Powder', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Nuts n Bolts', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Copper Ore', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Silver Ore', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Malachite Ore', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Obsidian Ore', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Brightcore Ore', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Spectrolite Ore', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Planks', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Quartz Crystal', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Rotating Gizmo', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Rough Ore', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Stringy Twine', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Simple Twine', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Sturdy Twine', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Peaky Twine', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Carved Twine', NULL)
INSERT INTO [dbo].[Materials] ([Description], [PictureId]) VALUES (N'Spectral Twine', NULL)